name = "dekodeglobalwebsite"
pages_build_output_dir = "dist"
compatibility_date = "2026-08-26"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "PROPOSAL_ASSETS"
bucket_name = "dekode-proposal-assets"
